# Generated by Django 5.2.8 on 2025-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de matrícula'),
        ),
    ]
