# Generated by Django 5.2.8 on 2025-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
