# Generated by Django 5.2.8 on 2025-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de no entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
