# Generated by Django 5.2.8 on 2025-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pedido_motivo_no_entrega_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
