# Generated by Django 5.2.8 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_multi_product_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='receta_omitida',
            field=models.BooleanField(default=False, verbose_name='Receta rechazada omitida por cliente'),
        ),
    ]
