# Generated by Django 5.2.8 on 2025-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_receta_omitida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de no entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_preparacion', 'En preparación'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50),
        ),
    ]
