# Generated by Django 5.2.8 on 2025-11-13 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_motivo_no_entrega_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'repartidor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PedidoRechazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_rechazo', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='pedidos.pedido')),
                ('repartidor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'repartidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_rechazo'],
                'unique_together': {('pedido', 'repartidor')},
            },
        ),
    ]
